<a href="https://colab.research.google.com/github/ankit05modak/pd-np-matplot-sklearn-training/blob/main/Python_loops_pandas_numpy_basicwrangling_advancewrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Programming for Data Science
### By Thomas Beuzen 
https://github.com/TomasBeuzen/python-programming-for-data-science/tree/main/practice-exercises

Solved...

## Python Basics

In [1]:
# What is 5 to the power of 5
#1 
pow(5, 5)

#2
5**5

3125

In [2]:
# What is the remainder from dividing 73 by 6?
76 % 6

4

In [3]:
# How many times does the whole number 3 go into 123? What is the remainder of dividing 123 by 3?
123 % 3, round(123 / 3)

(0, 41)

In [4]:
# Split the following string into a list by splitting on the space character:
s = "MDS is going virtual!"

s.split(" ")

['MDS', 'is', 'going', 'virtual!']

In [5]:
# Given the following variables:

thing = "light"
speed = 299792458  # m/s
# Use f-strings to print:
# The speed of light is 2.997925e+08 m/s.

print(f"The speed of the {thing} is {speed:2e} m/s")

The speed of the light is 2.997925e+08 m/s


In [6]:
# Given this nested list, use indexing to grab the word "MDS":
l = [10, [3, 4], [5, [100, 200, ["MDS"]], 23, 11], 1, 7]

l[2][1][2]

['MDS']

In [7]:
# Given this nest dictionary grab the word "MDS":
d = {
    "outer": [
        1,
        2,
        3,
        {"inner": ["this", "is", "inception", {"inner_inner": [1, 2, 3, "MDS"]}]},
    ]
}

d["outer"][3]["inner"][3]["inner_inner"][3]

'MDS'

In [8]:
# # Why does the following cell return an error?
# t = (1, 2, 3, 4, 5)
# t[-1] = 6

# # Because tuples are immutable. One cannot assign new values to a tuple.

In [9]:
# Use string methods to extract the website domain from an email, e.g., from the string "tomas.beuzen@fakemail.com", you should extract "fakemail".
email = "tomas.beuzen@fakemail.com"
# email.split(".")[1].split("@")[1]

# The above answer is less practical and logical because first we are splitting using "." which is very less likely to be in every email id's but "@" is going to be in every id followerd by .com
email.split("@")[-1].split(".com")[0]

'fakemail'

In [10]:
# Given the variable language which contains a string, use if/elif/else to write a program that:
# return "I love snakes!" if language is "python" (any kind of capitalization)
# return "Are you a pirate?" if language is "R" (any kind of capitalization)
# else return "What is language?" if language is anything else.


language = "python"
if language.lower() == "python":
  print("I love snakes!")
elif lanuage.lower() == "r":
  print("Are you a pirate?")
else:
  print("What is language?")


I love snakes!


## Loops and Functions

In [11]:
# Create a function website() that grabs the website domain from a url string. For example, if your function is passed "www.google.com", it should return "google".
def website(url):
  return url.split(".")[1]

website("www.google.com")

'google'

In [12]:
# Create a function divisible(a, b) that accepts two integers (a and b) and returns True if a is divisble by b without a remainder. 
# For example, divisible(10, 3) should return False, while divisible(6, 3) should return True.
def divisible(a, b):
  if a % b == 0:
    return True
  else:
    return False

divisible(10, 2)


True

In [13]:
# Use list comprehension to square every number in the following list of numbers.
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
d = [item**2 for item in l]
d

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [14]:
# For the following list of names, write a list comprehension that creates a list of only words that start with a capital letter (hint: str.isupper()).
names = ['Steve Irwin', 'koala', 'kangaroo', 'Australia', 'Sydney', 'desert']

[item for item in names if item[0].isupper()]

['Steve Irwin', 'Australia', 'Sydney']

In [15]:
# For the following list of keys and vals use dictionary comprehension to create a dictionary of the form {'key-0': 0, 'key-1': 1, etc} 
# (hint: zip() can help you combine two lists into on object to be used for comprehension/looping).

keys = [f"key-{k}" for k in range(10)]
vals = range(10)

{k:v for k, v in zip(keys, vals)}

{'key-0': 0,
 'key-1': 1,
 'key-2': 2,
 'key-3': 3,
 'key-4': 4,
 'key-5': 5,
 'key-6': 6,
 'key-7': 7,
 'key-8': 8,
 'key-9': 9}

In [16]:
# This question is a little harder. Create a generator function called listgen(n) that yields numbers from 0 to n, in batches of lists of maximum 10 numbers at a time. 
# For example, your function should behave as follows:

def listgen(n):
    counter = 0
    numbers = list(range(n))
    while counter <= n // 10:
        yield numbers[10 * counter:10*(counter+1)]
        counter += 1

g = listgen(5)

next(g)

[0, 1, 2, 3, 4]

In [17]:
# Write a try/except to catch the error generated from the following code and print “I caught you!”. 
# Make sure you catch the specific error being caused, this is typically better practice than just catching all errors!

try:
  5 / 0
except ZeroDivisionError:
  print("I caught you!")

I caught you!


In [18]:
# Create a function lucky_sum() that takes all the integers a user enters and returns their sum. However, if one of the values is 13 then it does not count towards the sum, nor do any values to its right.

# For example, your function should behave as follows:

# lucky_sum(1, 2, 3, 4)
# 10

# lucky_sum(1, 13, 3, 4)
# 1

# lucky_sum(13)

def lucky_sum(*args):
  if 13 in args:
    return sum(args[:args.index(13)])
  else:
    return sum(args)

lucky_sum(1, 13, 3, 4)

1

## Unit Test and Classes 

In [19]:
"""The function area() accepts the argument radius and calculates the area of a circle. Write three tests using assert statements for the following conditions:

Assert that area(1) returns a float;

Assert that area(0) returns a value of 0;

Assert that area(5) is approximately equal to 78.5 (hint: math.isclose(..., abs_tol=0.1))"""
import math
def area(radius):
  """Calculate the area of a circle based on the given radius."""
  return math.pi * radius ** 2

assert isinstance(area(1), float), "Test 1 failed"
assert area(0) == 0, "Test 2 failed"
assert math.isclose(area(5), 78.5, abs_tol=0.1), "Test 3 failed"

In [20]:
"""In the spirit of the EAFP (easier to ask for forgiveness than permission) philosophy. Modify the code of the function area() and add a 
try/except statement to catch the type error raised by passing a string to area() as shown below:"""

def area(radius):
  try:
    return math.pi * radius ** 2
  except TypeError:
    print(f"The radis is supposed to be a number but you entered {type(radius)}")
  else:
    print("Some error occured.")

area("5")

The radis is supposed to be a number but you entered <class 'str'>


In [21]:
"""In the spirit of the LBYL (look before you leap) philosophy. Modify the code of the function area() 
and add a conditional if/else statement to make sure that a user has passed a number (int or float) to the area() function. If they pass something else, raise a TypeError."""

def area(radius):
  if isinstance(radius, (int, float)):
    return math.pi * radius ** 2
  else:
    print(f"The type of radius should be a numerical value. But you entered {type(radius)}")

area(5)

78.53981633974483

In [22]:
"""
For this exercise I want you to create a class called circle. It should have the following characteristics:

It should be initiated with the argument radius and store this as an instance attribute.

Have a method area() which calculates the area of the circle.

Have a method circumference() which calculates the circumference of the circle.

Have the method __str__() which is a special method in Python and controls what is output to the screen when you print() an instance of your class (learn more here). 
The print() statement should print the string f"A Circle with radius {self.radius}".

I’ve provided some tests for you to check your class."""

class Circle:
  """A circle with a radius of r"""
  def __init__(self, radius):
    self.radius = radius

  def area(self):
    """Calculates area of the circle with given radius."""
    return math.pi * self.radius ** 2

  def circumference(self):
    """Calculated the circumference of the circle with given radius."""
    return 2 * math.pi * self.radius

  def __str__(self):
        return f"A Circle with radius {self.radius}"



In [23]:
assert Circle(3).radius == 3, "Test 1 failed."
assert math.isclose(Circle(3).area(), 28.3, abs_tol=0.1), "Test 2 failed."
assert math.isclose(Circle(3).circumference(), 18.8, abs_tol=0.1), "Test 3 failed."
assert Circle(3).__str__() == "A Circle with radius 3", "Test 4 failed."

In [24]:
"""Now, let’s create a new class sphere that inherits from the circle class we created above. It should have the following characteristics:

It should be initiated exactly the same as Circle was, with the single argument radius which is stored as an instance attribute.

Have a method volume() which calculates the volume of the sphere (43πr3).

Outputs the string f"A Sphere with volume 4.19" when you call print(Sphere(1)) (hint: recall the __str__() method from the previous question)."""

class Sphere(Circle):
  def volume(self):
    """Calculates volumeof the Sphere."""
    return 4 / 3 * math.pi * self.radius ** 3

  def __str__(self):
    return f"A Sphere with volume {self.volume():.2f}"


In [25]:
assert Sphere(3).radius == 3, "Test 1 failed."
assert math.isclose(Sphere(3).area(), 28.3, abs_tol=0.1), "Test 2 failed."
assert math.isclose(Sphere(3).circumference(), 18.8, abs_tol=0.1), "Test 3 failed."
assert math.isclose(Sphere(3).volume(), 113.1, abs_tol=0.1), "Test 3 failed."
assert Sphere(1).__str__() == "A Sphere with volume 4.19", "Test 4 failed."

## Numpy

In [26]:
# Import numpy under the alias np.
import numpy as np

In [27]:
# Create the following arrays:

"""Create an array of 5 zeros.
Create an array of 10 ones.
Create an array of 5 3.141s.
Create an array of the integers 1 to 20.
Create a 5 x 5 matrix of ones with a dtype int."""

print(np.zeros(5))
print(np.ones(10))
print(np.full(5, 3.141))
print(np.arange(1,21))
print(np.ones((5,5)))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3.141 3.141 3.141 3.141 3.141]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
# Use numpy to:

"""Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: np.random.randn())

Reshape the above array into shape (27,)"""

x = np.random.randn(3,3,3)
print(np.random.randn(3,3,3).reshape(27,))

[-2.63695765e-01  1.13413348e+00  1.37126440e+00  8.62320550e-01
  1.84364569e-01  8.96896864e-02 -6.19888218e-01  2.27124918e-01
  4.71740552e-01 -1.38801412e-01 -9.33630317e-04 -1.38913110e+00
  1.96341145e-02  2.27778916e+00  9.39424191e-01  2.75456705e+00
 -2.43507573e-01 -3.40444629e-01 -5.64571738e-01 -3.86330609e-01
  8.73945115e-01  1.02763018e-01 -1.65875508e+00 -5.30622005e-01
  2.30047063e+00 -2.34054806e-01 -1.05750264e+00]


In [29]:
# Create an array of 20 linearly spaced numbers between 1 and 10.

x = np.linspace(1,10,20)
x

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [30]:
# Below I’ve defined an array of shape 4 x 4. Use indexing to procude the given outputs.

a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
# 20
# a.shape
a[3][4]

20

In [32]:
# array([[ 9, 10],
#        [14, 15],
#        [19, 20],
#        [24, 25]])

a[1:,3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [33]:
# array([ 6,  7,  8,  9, 10])

a[1,:]

array([ 6,  7,  8,  9, 10])

In [34]:
# array([[11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20]])

a[2:4,]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
# array([[ 8,  9],
#        [13, 14]])

a[1:3, 2:4]

array([[ 8,  9],
       [13, 14]])

In [36]:
# Calculate the sum of all the numbers in a.

a.sum()

325

In [37]:
# Calculate the sum of each row in a.

a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [38]:
# Extract all values of a greater than the mean of a (hint: use a boolean mask).

a[a > a.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [39]:
# Find the location of the minimum value in the following array b:

np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [40]:
b.argmin()

6

In [41]:
# Find the location of the maximum value in the following 2D array c 

np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [42]:
c.argmax()

5

In [43]:
np.unravel_index(c.argmax(), c.shape)

(2, 1)

## Pandas

In [44]:
# Start by importing pandas with the alias pd.
import pandas as pd

In [45]:
"""
The dataset we'll be working with has the following columns:

column	description
country	Country Name
food_category	Food Category
consumption	Consumption (kg/person/year)
co2_emmission	Co2 Emission (Kg CO2/person/year)
Import the dataset as a dataframe named df from this url: https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"""

df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv")
df.head()

country food_category  consumption  co2_emmission
0  Argentina          Pork        10.51          37.20
1  Argentina       Poultry        38.66          41.53
2  Argentina          Beef        55.48        1712.00
3  Argentina   Lamb & Goat         1.56          54.63
4  Argentina          Fish         4.36           6.96

In [46]:
# How many rows and columns are there in the dataframe?

df.shape

(1430, 4)

In [47]:
# What is the type of data in each column of df?

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1430 entries, 0 to 1429
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   country        1430 non-null   object 
 1   food_category  1430 non-null   object 
 2   consumption    1430 non-null   float64
 3   co2_emmission  1430 non-null   float64
dtypes: float64(2), object(2)
memory usage: 44.8+ KB


In [48]:
df.dtypes

country           object
food_category     object
consumption      float64
co2_emmission    float64
dtype: object

In [49]:
# What is the mean co2_emission of the whole dataset?

df["co2_emmission"].mean()

74.383993006993

In [50]:
# How many different kinds of foods are there in the dataset? How many countries are in the dataset?

# df.food_category.value_counts().count()
# df['food_category'].nunique()

# df.country.value_counts().count()
df.country.nunique()

130

In [51]:
# What is the maximum co2_emmission in the dataset and which food type and country does it belong to?

df.iloc[df.co2_emmission.idxmax()]

country          Argentina
food_category         Beef
consumption          55.48
co2_emmission       1712.0
Name: 2, dtype: object

In [52]:
# How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

df.query("co2_emmission > 1000")

country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94

In [53]:
# Which country consumes the least amount of beef per person per year?

df.query("food_category == 'Beef'").sort_values(by="consumption").head(1)

country food_category  consumption  co2_emmission
1410  Liberia          Beef         0.78          24.07

In [54]:
# Which country consumes the most amount of soybeans per person per year?

df.query("food_category == 'Soybeans'").sort_values(by="consumption", ascending=False).head(1)

country food_category  consumption  co2_emmission
1010  Taiwan. ROC      Soybeans        16.95           7.63

In [55]:
# What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

meat = ['Poultry', 'Pork', 'Fish', 'Lamb & Goat', 'Beef']
df["co2_emmission"][df["food_category"].isin(meat)].sum()

74441.13

In [56]:
# What is the total emissions of all other (non-meat) products in the dataset combined?

meat = ['Poultry', 'Pork', 'Fish', 'Lamb & Goat', 'Beef']
df["co2_emmission"][~df["food_category"].isin(meat)].sum()

31927.98

## Basic Wrangling

In [57]:
# What country consumes the most food per person per year (across all food categories)?

df.groupby("country").sum().sort_values(by="consumption", ascending=False)[:1]

consumption  co2_emmission
country                            
Finland       639.79        1464.63

In [58]:
# Which food category is the biggest contributor to the above country's consumption total?
df.query("country == 'Finland'").sort_values(by="consumption", ascending=False)

country             food_category  consumption  co2_emmission
149  Finland        Milk - inc. cheese       430.76         613.57
150  Finland  Wheat and Wheat Products        81.99          15.64
143  Finland                      Pork        36.14         127.92
147  Finland                      Fish        33.80          53.97
144  Finland                   Poultry        19.87          21.34
145  Finland                      Beef        19.22         593.09
148  Finland                      Eggs         9.55           8.77
151  Finland                      Rice         4.42           5.66
153  Finland   Nuts inc. Peanut Butter         3.43           6.07
146  Finland               Lamb & Goat         0.53          18.56
152  Finland                  Soybeans         0.08           0.04

In [59]:
# What country produces the most kg C02 per person per year?
df.groupby("country").sum().sort_values(by="co2_emmission", ascending=False)

consumption  co2_emmission
country                                
Argentina         429.41        2172.40
Australia         465.09        1938.66
Albania           532.73        1777.85
New Zealand       360.92        1750.95
Iceland           472.31        1731.36
...                  ...            ...
Malawi             51.00         207.94
Liberia           131.04         203.38
Togo               74.32         188.09
Rwanda             40.38         181.63
Mozambique         63.41         141.40

[130 rows x 2 columns]

In [60]:
# Which food category is the biggest contributor to the above country’s C02 emissions?
df.query("country=='Argentina'").sort_values(by="co2_emmission", ascending=False)

country             food_category  consumption  co2_emmission
2   Argentina                      Beef        55.48        1712.00
6   Argentina        Milk - inc. cheese       195.08         277.87
3   Argentina               Lamb & Goat         1.56          54.63
1   Argentina                   Poultry        38.66          41.53
0   Argentina                      Pork        10.51          37.20
7   Argentina  Wheat and Wheat Products       103.11          19.66
8   Argentina                      Rice         8.77          11.22
5   Argentina                      Eggs        11.39          10.46
4   Argentina                      Fish         4.36           6.96
10  Argentina   Nuts inc. Peanut Butter         0.49           0.87
9   Argentina                  Soybeans         0.00           0.00

In [61]:
# What food category produces the most C02 per person per year across all countries?
df.groupby("food_category").sum().sort_values(by="co2_emmission", ascending=False)

consumption  co2_emmission
food_category                                       
Beef                          1576.04       48633.26
Milk - inc. cheese           16350.71       23290.00
Lamb & Goat                    338.02       11837.38
Pork                          2096.08        7419.11
Rice                          3818.77        4886.91
Fish                          2247.32        3588.22
Poultry                       2758.50        2963.16
Wheat and Wheat Products      9301.44        1773.78
Eggs                          1061.29         974.95
Nuts inc. Peanut Butter        537.84         951.99
Soybeans                       111.87          50.35

In [62]:
# What food category is consumed the most across all countries per person per year? What food category is consumed the least across all countries?

print(f'Least comsumption:{df.groupby("food_category").sum().sort_values(by="consumption").head(1)}')
print(f"Most consumtion: {df.groupby('food_category').sum().sort_values(by='consumption').tail(1)}")

Least comsumption:               consumption  co2_emmission
food_category                            
Soybeans            111.87          50.35
Most consumtion:                     consumption  co2_emmission
food_category                                 
Milk - inc. cheese     16350.71        23290.0


In [63]:
# Make the dataset wide by pivoting on the food_category column. You’ll end up with a “multi-index” dataframe, with multiple levels of columns.

pt = df.pivot(index="country", columns="food_category")
pt.T

country                                 Albania  Algeria  Angola  Argentina  \
              food_category                                                   
consumption   Beef                        22.50     5.60    8.42      55.48   
              Eggs                        12.45     8.06    1.11      11.39   
              Fish                         3.85     3.74   15.24       4.36   
              Lamb & Goat                 15.32     7.69    1.08       1.56   
              Milk - inc. cheese         303.72   141.53   12.30     195.08   
              Nuts inc. Peanut Butter      4.36     2.08    2.26       0.49   
              Pork                        10.88     0.00    8.89      10.51   
              Poultry                     13.23     7.42   17.33      38.66   
              Rice                         7.78     2.97    8.12       8.77   
              Soybeans                     0.00     0.00    0.52       0.00   
              Wheat and Wheat Products   138.64   185.42   40.72     103.11   
co2_emmission Beef                       694.30   172.80  259.82    1712.00   
              Eggs                        11.44     7.40    1.02      10.46   
              Fish                         6.15     5.97   24.33       6.96   
              Lamb & Goat                536.50   269.30   37.82      54.63   
              Milk - inc. cheese         432.62   201.60   17.52     277.87   
              Nuts inc. Peanut Butter      7.72     3.68    4.00       0.87   
              Pork                        38.51     0.00   31.47      37.20   
              Poultry                     14.21     7.97   18.62      41.53   
              Rice                         9.96     3.80   10.39      11.22   
              Soybeans                     0.00     0.00    0.23       0.00   
              Wheat and Wheat Products    26.44    35.36    7.77      19.66   

country                                 Armenia  Australia  Austria  Bahamas  \
              food_category                                                    
consumption   Beef                        19.66      33.86    17.14    19.92   
              Eggs                        11.69       8.51    14.68     6.20   
              Fish                         4.36      17.69    12.16    18.80   
              Lamb & Goat                  3.02       9.87     1.16     5.22   
              Milk - inc. cheese         209.03     234.49   258.09   104.76   
              Nuts inc. Peanut Butter      2.55       8.73     7.88     4.03   
              Pork                         9.67      24.14    52.56    32.74   
              Poultry                     13.35      46.12    18.61    45.74   
              Rice                         3.18      11.03     3.70    23.97   
              Soybeans                     0.00       0.19     2.06     0.09   
              Wheat and Wheat Products   130.60      70.46    81.10    39.98   
co2_emmission Beef                       606.67    1044.85   528.90   614.69   
              Eggs                        10.74       7.82    13.49     5.70   
              Fish                         6.96      28.25    19.42    30.02   
              Lamb & Goat                105.76     345.65    40.62   182.80   
              Milk - inc. cheese         297.74     334.01   367.62   149.22   
              Nuts inc. Peanut Butter      4.51      15.45    13.95     7.13   
              Pork                        34.23      85.44   186.04   115.88   
              Poultry                     14.34      49.54    19.99    49.13   
              Rice                         4.07      14.12     4.73    30.67   
              Soybeans                     0.00       0.09     0.93     0.04   
              Wheat and Wheat Products    24.91      13.44    15.47     7.62   

country                                 Bangladesh  Barbados  ...      USA  \
              food_category                                   ...            
consumption   Beef        

## Advance wrangling with Pandas

In [85]:
 link = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv"
 df = pd.read_csv(link)
# We only required following columns
req_cols = ["password", "value", "time_unit"]

df[req_cols]

password  value time_unit
0    password   6.91     years
1      123456  18.52   minutes
2    12345678   1.29      days
3        1234  11.11   seconds
4      qwerty   3.72      days
..        ...    ...       ...
502       NaN    NaN       NaN
503       NaN    NaN       NaN
504       NaN    NaN       NaN
505       NaN    NaN       NaN
506       NaN    NaN       NaN

[507 rows x 3 columns]

In [88]:
# We only required following columns
req_cols = ["password", "value", "time_unit"]

# Import using only these columns
df1 = pd.read_csv(link, usecols=req_cols, skipfooter=7, engine="python")
df1

password  value time_unit
0    password   6.91     years
1      123456  18.52   minutes
2    12345678   1.29      days
3        1234  11.11   seconds
4      qwerty   3.72      days
..        ...    ...       ...
495    reddog   3.72      days
496  alexande   6.91     years
497   college   3.19    months
498    jester   3.72      days
499  passw0rd  92.27     years

[500 rows x 3 columns]

In [89]:
"""
An online password attack is when someone tries to hack your account by simply trying a very large number of username/password combinations to access your account. 
For each password in our dataset, the value column shows the amount of time it is estimated to take an "online password attack" to hack your account. 
The column time_unit shows the units of that time value (e.g., hours, days, years, etc.)

It would be much nicer if our values were of the same units so we can more easily compare the "online password guessing time" for each password. 
So your first task is to convert all of the values to units of hours (assume the conversion units I've provided below, e.g., 1 day is 24 hours, 1 week is 168 hours, etc).
"""

units = {
    "seconds" : 1/360,
    "minutes" : 1/60,
    "days": 24,
    "weeks": 24*7,
    "months": 720,
    "years": 8760
}

for key, value in units.items():
  df1.loc[df1["time_unit"] == key, "value"] *= value

df1["time_unit"] = "hours"
df1

password          value time_unit
0    password   60531.600000     hours
1      123456       0.308667     hours
2    12345678      30.960000     hours
3        1234       0.030861     hours
4      qwerty      89.280000     hours
..        ...            ...       ...
495    reddog      89.280000     hours
496  alexande   60531.600000     hours
497   college    2296.800000     hours
498    jester      89.280000     hours
499  passw0rd  808285.200000     hours

[500 rows x 3 columns]

In [94]:
# How many password begin with the sequence 123?

df1["password"].str.contains(r"^123").sum()

9